system:
  data:
    postgres:
      host: localhost
      database: amakhosi_pumps
      user: postgres
      pwd:  root
      port: 5432
      url: postgresql://%s:%s@%s:%d/%s?sslmode=disable
webserver:
  port: 8002
twilio:
  sid:  
  token:  
  number: 15045798139
mongodatabase:
  uri: mongodb://localhost:27017
rabbit:
  url: amqp://guest:P@ssw0rd@localhost:5672/
sendgrid:
  api: 
  from: robson@stima.co.za
