system:
  data:
    postgres:
      host: localhost
      database: amakhosi_pumps
      user: postgres
      pwd:  root
      port: 5432
      url: postgresql://%s:%s@%s:%d/%s?sslmode=disable
webserver:
  port: 8002

