// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sensors/sensors.proto

package sensors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SensorRequest struct {
	SensorName           string   `protobuf:"bytes,1,opt,name=sensorName,proto3" json:"sensorName,omitempty"`
	SerialNumber         string   `protobuf:"bytes,2,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SensorRequest) Reset()         { *m = SensorRequest{} }
func (m *SensorRequest) String() string { return proto.CompactTextString(m) }
func (*SensorRequest) ProtoMessage()    {}
func (*SensorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ecade768b06d2a, []int{0}
}

func (m *SensorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorRequest.Unmarshal(m, b)
}
func (m *SensorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorRequest.Marshal(b, m, deterministic)
}
func (m *SensorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorRequest.Merge(m, src)
}
func (m *SensorRequest) XXX_Size() int {
	return xxx_messageInfo_SensorRequest.Size(m)
}
func (m *SensorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SensorRequest proto.InternalMessageInfo

func (m *SensorRequest) GetSensorName() string {
	if m != nil {
		return m.SensorName
	}
	return ""
}

func (m *SensorRequest) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *SensorRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SensorResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SensorResponse) Reset()         { *m = SensorResponse{} }
func (m *SensorResponse) String() string { return proto.CompactTextString(m) }
func (*SensorResponse) ProtoMessage()    {}
func (*SensorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ecade768b06d2a, []int{1}
}

func (m *SensorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorResponse.Unmarshal(m, b)
}
func (m *SensorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorResponse.Marshal(b, m, deterministic)
}
func (m *SensorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorResponse.Merge(m, src)
}
func (m *SensorResponse) XXX_Size() int {
	return xxx_messageInfo_SensorResponse.Size(m)
}
func (m *SensorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SensorResponse proto.InternalMessageInfo

func (m *SensorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SensorRequest)(nil), "sensors.SensorRequest")
	proto.RegisterType((*SensorResponse)(nil), "sensors.SensorResponse")
}

func init() { proto.RegisterFile("sensors/sensors.proto", fileDescriptor_e9ecade768b06d2a) }

var fileDescriptor_e9ecade768b06d2a = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0x43, 0x31,
	0x10, 0xc4, 0xad, 0x62, 0x8b, 0x8b, 0x7a, 0x08, 0x56, 0x83, 0x07, 0x91, 0x20, 0x22, 0x1e, 0xde,
	0x03, 0xfd, 0x06, 0xde, 0xf4, 0xd0, 0x43, 0xeb, 0xc9, 0x5b, 0x62, 0xd7, 0x1a, 0x6c, 0xfe, 0x98,
	0xcd, 0xf6, 0xf3, 0x0b, 0xc9, 0x0b, 0xf8, 0xe8, 0x29, 0xf9, 0xcd, 0x0e, 0x0c, 0x33, 0x30, 0x27,
	0xf4, 0x14, 0x12, 0xf5, 0xc3, 0xdb, 0xc5, 0x14, 0x72, 0x10, 0xb3, 0x01, 0x95, 0x85, 0xb3, 0x55,
	0xf9, 0x2e, 0xf1, 0x97, 0x91, 0xb2, 0xb8, 0x01, 0xa8, 0xb7, 0x85, 0x76, 0x28, 0x27, 0xb7, 0x93,
	0x87, 0x93, 0xe5, 0x3f, 0x45, 0x28, 0x38, 0x25, 0x4c, 0x56, 0x6f, 0x17, 0xec, 0x0c, 0x26, 0x79,
	0x58, 0x1c, 0x23, 0x4d, 0x5c, 0xc0, 0xf1, 0x4e, 0x6f, 0x19, 0xe5, 0x51, 0x39, 0x56, 0x50, 0x8f,
	0x70, 0xde, 0xa2, 0x28, 0x06, 0x4f, 0x28, 0x24, 0xcc, 0x1c, 0x12, 0xe9, 0x4d, 0x0b, 0x6a, 0xf8,
	0xf4, 0x0e, 0xd3, 0xea, 0x15, 0x6f, 0x30, 0x5f, 0xa1, 0x5f, 0x57, 0x7a, 0xf5, 0x5f, 0x21, 0x39,
	0x9d, 0x6d, 0xf0, 0xe2, 0xb2, 0x6b, 0x95, 0x46, 0x05, 0xae, 0xaf, 0xf6, 0xf4, 0x9a, 0xa6, 0x0e,
	0x5e, 0xee, 0x3f, 0xee, 0x36, 0x36, 0x7f, 0xb3, 0xe9, 0x3e, 0x83, 0xeb, 0x93, 0xe3, 0x1f, 0x36,
	0x3b, 0xee, 0x23, 0xbb, 0xb8, 0xd6, 0x59, 0xb7, 0x8d, 0xcc, 0xb4, 0x8c, 0xf4, 0xfc, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x76, 0x57, 0x8b, 0xb9, 0x3d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SensorClient is the client API for Sensor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SensorClient interface {
	SendSensorInformation(ctx context.Context, in *SensorRequest, opts ...grpc.CallOption) (*SensorResponse, error)
}

type sensorClient struct {
	cc *grpc.ClientConn
}

func NewSensorClient(cc *grpc.ClientConn) SensorClient {
	return &sensorClient{cc}
}

func (c *sensorClient) SendSensorInformation(ctx context.Context, in *SensorRequest, opts ...grpc.CallOption) (*SensorResponse, error) {
	out := new(SensorResponse)
	err := c.cc.Invoke(ctx, "/sensors.Sensor/SendSensorInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorServer is the server API for Sensor service.
type SensorServer interface {
	SendSensorInformation(context.Context, *SensorRequest) (*SensorResponse, error)
}

func RegisterSensorServer(s *grpc.Server, srv SensorServer) {
	s.RegisterService(&_Sensor_serviceDesc, srv)
}

func _Sensor_SendSensorInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServer).SendSensorInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sensors.Sensor/SendSensorInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServer).SendSensorInformation(ctx, req.(*SensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sensor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sensors.Sensor",
	HandlerType: (*SensorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSensorInformation",
			Handler:    _Sensor_SendSensorInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sensors/sensors.proto",
}
